--------------------------------------------------------
-- Archivo creado  - lunes-septiembre-30-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOLETA
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."BOLETA" 
   (	"IDBOLETA" NUMBER, 
	"FECPAGO" DATE, 
	"FECLIMITE" DATE, 
	"MONTO" NUMBER, 
	"ESTADOBOLETA" NUMBER, 
	"IDPLAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CAPACITACION
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."CAPACITACION" 
   (	"IDCAPACITACION" NUMBER, 
	"FECHA" DATE, 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"CANTASISTENTES" NUMBER, 
	"IDPLAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHECKLIST
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."CHECKLIST" 
   (	"IDCHECK" NUMBER, 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"IDPLAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHECKLISTREPORTE
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."CHECKLISTREPORTE" 
   (	"IDCHECKREPORTE" NUMBER, 
	"ESTADOCHECK" NUMBER, 
	"FECHA" DATE, 
	"MEJORA" VARCHAR2(150 BYTE), 
	"IDCHECKLIST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CIUDAD
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."CIUDAD" 
   (	"IDCIUDAD" NUMBER, 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."CLIENTE" 
   (	"IDCLIENTE" NUMBER, 
	"RUT" VARCHAR2(11 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APEPATERNO" VARCHAR2(30 BYTE), 
	"APEMATERNO" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(12 BYTE), 
	"IDCOMUNA" NUMBER, 
	"IDRUBRO" NUMBER, 
	"IDUSUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."COMUNA" 
   (	"IDCOMUNA" NUMBER, 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"IDCIUDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLEBOLETA
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."DETALLEBOLETA" 
   (	"IDDETALLEBOLETA" NUMBER, 
	"PRECIO" NUMBER, 
	"IDBOLETA" NUMBER, 
	"IDSERVICIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTO
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."EVENTO" 
   (	"IDEVENTO" NUMBER, 
	"ASESORIA" VARCHAR2(255 BYTE), 
	"FECHA" DATE, 
	"IDTIPOEVENTO" NUMBER, 
	"IDPLAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODIFICACIONCHECK
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."MODIFICACIONCHECK" 
   (	"IDMODIFICACION" NUMBER, 
	"FECHA" DATE, 
	"IDCHECK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANCONTRATADO
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."PLANCONTRATADO" 
   (	"IDPLAN" NUMBER, 
	"FECPLAN" DATE, 
	"PRECIO" NUMBER, 
	"SUCURSAL" VARCHAR2(100 BYTE), 
	"ESTADO" NUMBER, 
	"IDCLIENTE" NUMBER, 
	"IDPROFESIONAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFESIONAL
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."PROFESIONAL" 
   (	"IDPROFESIONAL" NUMBER, 
	"RUT" VARCHAR2(11 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APEPATERNO" VARCHAR2(30 BYTE), 
	"APEMATERNO" VARCHAR2(30 BYTE), 
	"TELEFONO" VARCHAR2(12 BYTE), 
	"FECNACIMIENTO" DATE, 
	"IDCOMUNA" NUMBER, 
	"IDUBICACION" NUMBER, 
	"IDUSUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPORTE
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."REPORTE" 
   (	"IDREPORTE" NUMBER, 
	"VISITAS" NUMBER, 
	"CAPACITACION" NUMBER, 
	"ACCIDENTES" NUMBER, 
	"MULTAS" NUMBER, 
	"IDUSUADMIN" NUMBER, 
	"IDCLIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RUBRO
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."RUBRO" 
   (	"IDRUBRO" NUMBER, 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICIO
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."SERVICIO" 
   (	"IDSERVICIO" NUMBER, 
	"DESCRIPCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPOEVENTO
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."TIPOEVENTO" 
   (	"IDTIPOEVENTO" NUMBER, 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPOUSUARIO
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."TIPOUSUARIO" 
   (	"IDTIPOUSUARIO" NUMBER, 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UBICACION
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."UBICACION" 
   (	"IDUBICACION" NUMBER, 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "NOMASACC"."USUARIO" 
   (	"IDUSUARIO" NUMBER, 
	"USU" VARCHAR2(30 BYTE), 
	"PASS" VARCHAR2(255 BYTE), 
	"ESTADOUSUARIO" NUMBER, 
	"IDTIPOUSUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NOMASACC.BOLETA
SET DEFINE OFF;
REM INSERTING into NOMASACC.CAPACITACION
SET DEFINE OFF;
REM INSERTING into NOMASACC.CHECKLIST
SET DEFINE OFF;
REM INSERTING into NOMASACC.CHECKLISTREPORTE
SET DEFINE OFF;
REM INSERTING into NOMASACC.CIUDAD
SET DEFINE OFF;
REM INSERTING into NOMASACC.CLIENTE
SET DEFINE OFF;
REM INSERTING into NOMASACC.COMUNA
SET DEFINE OFF;
REM INSERTING into NOMASACC.DETALLEBOLETA
SET DEFINE OFF;
REM INSERTING into NOMASACC.EVENTO
SET DEFINE OFF;
REM INSERTING into NOMASACC.MODIFICACIONCHECK
SET DEFINE OFF;
REM INSERTING into NOMASACC.PLANCONTRATADO
SET DEFINE OFF;
REM INSERTING into NOMASACC.PROFESIONAL
SET DEFINE OFF;
REM INSERTING into NOMASACC.REPORTE
SET DEFINE OFF;
REM INSERTING into NOMASACC.RUBRO
SET DEFINE OFF;
REM INSERTING into NOMASACC.SERVICIO
SET DEFINE OFF;
REM INSERTING into NOMASACC.TIPOEVENTO
SET DEFINE OFF;
REM INSERTING into NOMASACC.TIPOUSUARIO
SET DEFINE OFF;
REM INSERTING into NOMASACC.UBICACION
SET DEFINE OFF;
REM INSERTING into NOMASACC.USUARIO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CIUDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."CIUDAD_PK" ON "NOMASACC"."CIUDAD" ("IDCIUDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDDETALLEBOLETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."IDDETALLEBOLETA" ON "NOMASACC"."DETALLEBOLETA" ("IDDETALLEBOLETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHECK_REPORTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."CHECK_REPORTE_PK" ON "NOMASACC"."CHECKLISTREPORTE" ("IDCHECKREPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_EVENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."TIPO_EVENTO_PK" ON "NOMASACC"."TIPOEVENTO" ("IDTIPOEVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPORTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."REPORTE_PK" ON "NOMASACC"."REPORTE" ("IDREPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOLETA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."BOLETA_PK" ON "NOMASACC"."BOLETA" ("IDBOLETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHECK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."CHECK_PK" ON "NOMASACC"."CHECKLIST" ("IDCHECK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RUBRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."RUBRO_PK" ON "NOMASACC"."RUBRO" ("IDRUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PLAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."PLAN_PK" ON "NOMASACC"."PLANCONTRATADO" ("IDPLAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMUNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."COMUNA_PK" ON "NOMASACC"."COMUNA" ("IDCOMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MODCHECK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."MODCHECK_PK" ON "NOMASACC"."MODIFICACIONCHECK" ("IDMODIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERVICIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."SERVICIO_PK" ON "NOMASACC"."SERVICIO" ("IDSERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."CLIENTE_PK" ON "NOMASACC"."CLIENTE" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CAPACITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."CAPACITACION_PK" ON "NOMASACC"."CAPACITACION" ("IDCAPACITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."TIPO_USUARIO_PK" ON "NOMASACC"."TIPOUSUARIO" ("IDTIPOUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."PROFESIONAL_PK" ON "NOMASACC"."PROFESIONAL" ("IDPROFESIONAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."EVENTO_PK" ON "NOMASACC"."EVENTO" ("IDEVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UBICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."UBICACION_PK" ON "NOMASACC"."UBICACION" ("IDUBICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOMASACC"."USUARIO_PK" ON "NOMASACC"."USUARIO" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPOUSUARIO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."TIPOUSUARIO" ADD CONSTRAINT "TIPO_USUARIO_PK" PRIMARY KEY ("IDTIPOUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."TIPOUSUARIO" MODIFY ("IDTIPOUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODIFICACIONCHECK
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."MODIFICACIONCHECK" ADD CONSTRAINT "MODCHECK_PK" PRIMARY KEY ("IDMODIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."MODIFICACIONCHECK" MODIFY ("IDCHECK" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."MODIFICACIONCHECK" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."MODIFICACIONCHECK" MODIFY ("IDMODIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAPACITACION
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CAPACITACION" ADD CONSTRAINT "CAPACITACION_PK" PRIMARY KEY ("IDCAPACITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."CAPACITACION" MODIFY ("IDPLAN" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CAPACITACION" MODIFY ("CANTASISTENTES" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CAPACITACION" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CAPACITACION" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CAPACITACION" MODIFY ("IDCAPACITACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANCONTRATADO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."PLANCONTRATADO" ADD CONSTRAINT "PLAN_PK" PRIMARY KEY ("IDPLAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" MODIFY ("IDPROFESIONAL" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" MODIFY ("SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" MODIFY ("FECPLAN" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" MODIFY ("IDPLAN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHECKLISTREPORTE
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CHECKLISTREPORTE" ADD CONSTRAINT "CHECK_REPORTE_PK" PRIMARY KEY ("IDCHECKREPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."CHECKLISTREPORTE" MODIFY ("IDCHECKLIST" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CHECKLISTREPORTE" MODIFY ("MEJORA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CHECKLISTREPORTE" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CHECKLISTREPORTE" MODIFY ("ESTADOCHECK" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CHECKLISTREPORTE" MODIFY ("IDCHECKREPORTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."USUARIO" MODIFY ("IDTIPOUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."USUARIO" MODIFY ("ESTADOUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."USUARIO" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."USUARIO" MODIFY ("USU" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."USUARIO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOEVENTO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."TIPOEVENTO" ADD CONSTRAINT "TIPO_EVENTO_PK" PRIMARY KEY ("IDTIPOEVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."TIPOEVENTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."TIPOEVENTO" MODIFY ("IDTIPOEVENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHECKLIST
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CHECKLIST" ADD CONSTRAINT "CHECK_PK" PRIMARY KEY ("IDCHECK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."CHECKLIST" MODIFY ("IDPLAN" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CHECKLIST" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CHECKLIST" MODIFY ("IDCHECK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOLETA
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."BOLETA" ADD CONSTRAINT "BOLETA_PK" PRIMARY KEY ("IDBOLETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."BOLETA" MODIFY ("IDPLAN" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."BOLETA" MODIFY ("ESTADOBOLETA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."BOLETA" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."BOLETA" MODIFY ("FECLIMITE" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."BOLETA" MODIFY ("FECPAGO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."BOLETA" MODIFY ("IDBOLETA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("IDRUBRO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("APEMATERNO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("APEPATERNO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CLIENTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UBICACION
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."UBICACION" ADD CONSTRAINT "UBICACION_PK" PRIMARY KEY ("IDUBICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."UBICACION" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."UBICACION" MODIFY ("DIRECCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."SERVICIO" ADD CONSTRAINT "SERVICIO_PK" PRIMARY KEY ("IDSERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."SERVICIO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."SERVICIO" MODIFY ("IDSERVICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUBRO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."RUBRO" ADD CONSTRAINT "RUBRO_PK" PRIMARY KEY ("IDRUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."RUBRO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."RUBRO" MODIFY ("IDRUBRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."COMUNA" ADD CONSTRAINT "COMUNA_PK" PRIMARY KEY ("IDCOMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."COMUNA" MODIFY ("IDCIUDAD" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."COMUNA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."COMUNA" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CIUDAD
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CIUDAD" ADD CONSTRAINT "CIUDAD_PK" PRIMARY KEY ("IDCIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."CIUDAD" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."CIUDAD" MODIFY ("IDCIUDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."EVENTO" ADD CONSTRAINT "EVENTO_PK" PRIMARY KEY ("IDEVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."EVENTO" MODIFY ("IDPLAN" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."EVENTO" MODIFY ("IDTIPOEVENTO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."EVENTO" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."EVENTO" MODIFY ("ASESORIA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."EVENTO" MODIFY ("IDEVENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORTE
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."REPORTE" ADD CONSTRAINT "REPORTE_PK" PRIMARY KEY ("IDREPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."REPORTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."REPORTE" MODIFY ("IDUSUADMIN" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."REPORTE" MODIFY ("MULTAS" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."REPORTE" MODIFY ("ACCIDENTES" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."REPORTE" MODIFY ("CAPACITACION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."REPORTE" MODIFY ("VISITAS" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."REPORTE" MODIFY ("IDREPORTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESIONAL
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."PROFESIONAL" ADD CONSTRAINT "PROFESIONAL_PK" PRIMARY KEY ("IDPROFESIONAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("IDUBICACION" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("FECNACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("APEMATERNO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("APEPATERNO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."PROFESIONAL" MODIFY ("IDPROFESIONAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLEBOLETA
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."DETALLEBOLETA" ADD CONSTRAINT "IDDETALLEBOLETA" PRIMARY KEY ("IDDETALLEBOLETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOMASACC"."DETALLEBOLETA" MODIFY ("IDSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."DETALLEBOLETA" MODIFY ("IDBOLETA" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."DETALLEBOLETA" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "NOMASACC"."DETALLEBOLETA" MODIFY ("IDDETALLEBOLETA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOLETA
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."BOLETA" ADD CONSTRAINT "PLAN_FK" FOREIGN KEY ("IDPLAN")
	  REFERENCES "NOMASACC"."PLANCONTRATADO" ("IDPLAN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAPACITACION
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CAPACITACION" ADD CONSTRAINT "CAPACITACION_PLAN_FK" FOREIGN KEY ("IDPLAN")
	  REFERENCES "NOMASACC"."PLANCONTRATADO" ("IDPLAN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHECKLIST
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CHECKLIST" ADD CONSTRAINT "CHECK_PLAN_FK" FOREIGN KEY ("IDPLAN")
	  REFERENCES "NOMASACC"."PLANCONTRATADO" ("IDPLAN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHECKLISTREPORTE
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CHECKLISTREPORTE" ADD CONSTRAINT "CHECKLIST_FK" FOREIGN KEY ("IDCHECKLIST")
	  REFERENCES "NOMASACC"."CHECKLIST" ("IDCHECK") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."CLIENTE" ADD CONSTRAINT "CLI_COMUNA_FK" FOREIGN KEY ("IDCOMUNA")
	  REFERENCES "NOMASACC"."COMUNA" ("IDCOMUNA") ENABLE;
  ALTER TABLE "NOMASACC"."CLIENTE" ADD CONSTRAINT "CLI_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "NOMASACC"."USUARIO" ("IDUSUARIO") ENABLE;
  ALTER TABLE "NOMASACC"."CLIENTE" ADD CONSTRAINT "RUBRO_FK" FOREIGN KEY ("IDRUBRO")
	  REFERENCES "NOMASACC"."RUBRO" ("IDRUBRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."COMUNA" ADD CONSTRAINT "COMUNA_CIUDAD_FK" FOREIGN KEY ("IDCIUDAD")
	  REFERENCES "NOMASACC"."CIUDAD" ("IDCIUDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLEBOLETA
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."DETALLEBOLETA" ADD CONSTRAINT "BOLETA_FK" FOREIGN KEY ("IDBOLETA")
	  REFERENCES "NOMASACC"."BOLETA" ("IDBOLETA") ENABLE;
  ALTER TABLE "NOMASACC"."DETALLEBOLETA" ADD CONSTRAINT "SERVICIO_FK" FOREIGN KEY ("IDSERVICIO")
	  REFERENCES "NOMASACC"."SERVICIO" ("IDSERVICIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."EVENTO" ADD CONSTRAINT "EVENTO_PLAN_FK" FOREIGN KEY ("IDPLAN")
	  REFERENCES "NOMASACC"."PLANCONTRATADO" ("IDPLAN") ENABLE;
  ALTER TABLE "NOMASACC"."EVENTO" ADD CONSTRAINT "TIPO_EVENTO_FK" FOREIGN KEY ("IDTIPOEVENTO")
	  REFERENCES "NOMASACC"."TIPOEVENTO" ("IDTIPOEVENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODIFICACIONCHECK
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."MODIFICACIONCHECK" ADD CONSTRAINT "MOD_CHECK_FK" FOREIGN KEY ("IDCHECK")
	  REFERENCES "NOMASACC"."CHECKLIST" ("IDCHECK") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANCONTRATADO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."PLANCONTRATADO" ADD CONSTRAINT "CLIENTE_FK" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "NOMASACC"."CLIENTE" ("IDCLIENTE") ENABLE;
  ALTER TABLE "NOMASACC"."PLANCONTRATADO" ADD CONSTRAINT "PROFESIONAL_FK" FOREIGN KEY ("IDPROFESIONAL")
	  REFERENCES "NOMASACC"."PROFESIONAL" ("IDPROFESIONAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFESIONAL
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."PROFESIONAL" ADD CONSTRAINT "PROF_COMUNA_FK" FOREIGN KEY ("IDCOMUNA")
	  REFERENCES "NOMASACC"."COMUNA" ("IDCOMUNA") ENABLE;
  ALTER TABLE "NOMASACC"."PROFESIONAL" ADD CONSTRAINT "PROF_USUARIO_FK" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "NOMASACC"."USUARIO" ("IDUSUARIO") ENABLE;
  ALTER TABLE "NOMASACC"."PROFESIONAL" ADD CONSTRAINT "UBICACION_FK" FOREIGN KEY ("IDUBICACION")
	  REFERENCES "NOMASACC"."UBICACION" ("IDUBICACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORTE
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."REPORTE" ADD CONSTRAINT "REPORTE_CLIENTE_FK" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "NOMASACC"."CLIENTE" ("IDCLIENTE") ENABLE;
  ALTER TABLE "NOMASACC"."REPORTE" ADD CONSTRAINT "REPORTE_USUARIO_FK" FOREIGN KEY ("IDUSUADMIN")
	  REFERENCES "NOMASACC"."USUARIO" ("IDUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "NOMASACC"."USUARIO" ADD CONSTRAINT "TIPO_USUARIO_FK" FOREIGN KEY ("IDTIPOUSUARIO")
	  REFERENCES "NOMASACC"."TIPOUSUARIO" ("IDTIPOUSUARIO") ENABLE;
