//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAcc2._0.ServicioReportes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteCliente", Namespace="http://schemas.datacontract.org/2004/07/DALC.modelo")]
    [System.SerializableAttribute()]
    public partial class ReporteCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int accidentesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int capacitacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idReporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int multasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreProfesionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutProfesionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int visitasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int accidentes {
            get {
                return this.accidentesField;
            }
            set {
                if ((this.accidentesField.Equals(value) != true)) {
                    this.accidentesField = value;
                    this.RaisePropertyChanged("accidentes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacitaciones {
            get {
                return this.capacitacionesField;
            }
            set {
                if ((this.capacitacionesField.Equals(value) != true)) {
                    this.capacitacionesField = value;
                    this.RaisePropertyChanged("capacitaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empresa {
            get {
                return this.empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.empresaField, value) != true)) {
                    this.empresaField = value;
                    this.RaisePropertyChanged("empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporte {
            get {
                return this.idReporteField;
            }
            set {
                if ((this.idReporteField.Equals(value) != true)) {
                    this.idReporteField = value;
                    this.RaisePropertyChanged("idReporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int multas {
            get {
                return this.multasField;
            }
            set {
                if ((this.multasField.Equals(value) != true)) {
                    this.multasField = value;
                    this.RaisePropertyChanged("multas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreClienteField, value) != true)) {
                    this.nombreClienteField = value;
                    this.RaisePropertyChanged("nombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreProfesional {
            get {
                return this.nombreProfesionalField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreProfesionalField, value) != true)) {
                    this.nombreProfesionalField = value;
                    this.RaisePropertyChanged("nombreProfesional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rutCliente {
            get {
                return this.rutClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.rutClienteField, value) != true)) {
                    this.rutClienteField = value;
                    this.RaisePropertyChanged("rutCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rutProfesional {
            get {
                return this.rutProfesionalField;
            }
            set {
                if ((object.ReferenceEquals(this.rutProfesionalField, value) != true)) {
                    this.rutProfesionalField = value;
                    this.RaisePropertyChanged("rutProfesional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int visitas {
            get {
                return this.visitasField;
            }
            set {
                if ((this.visitasField.Equals(value) != true)) {
                    this.visitasField = value;
                    this.RaisePropertyChanged("visitas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteGlobal", Namespace="http://schemas.datacontract.org/2004/07/DALC.modelo")]
    [System.SerializableAttribute()]
    public partial class ReporteGlobal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidad_clientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantidad_profesionalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idReporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int planes_activosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int planes_inactivosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad_clientes {
            get {
                return this.cantidad_clientesField;
            }
            set {
                if ((this.cantidad_clientesField.Equals(value) != true)) {
                    this.cantidad_clientesField = value;
                    this.RaisePropertyChanged("cantidad_clientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad_profesionales {
            get {
                return this.cantidad_profesionalesField;
            }
            set {
                if ((this.cantidad_profesionalesField.Equals(value) != true)) {
                    this.cantidad_profesionalesField = value;
                    this.RaisePropertyChanged("cantidad_profesionales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReporte {
            get {
                return this.idReporteField;
            }
            set {
                if ((this.idReporteField.Equals(value) != true)) {
                    this.idReporteField = value;
                    this.RaisePropertyChanged("idReporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int planes_activos {
            get {
                return this.planes_activosField;
            }
            set {
                if ((this.planes_activosField.Equals(value) != true)) {
                    this.planes_activosField = value;
                    this.RaisePropertyChanged("planes_activos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int planes_inactivos {
            get {
                return this.planes_inactivosField;
            }
            set {
                if ((this.planes_inactivosField.Equals(value) != true)) {
                    this.planes_inactivosField = value;
                    this.RaisePropertyChanged("planes_inactivos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioReportes.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ingresarReporte", ReplyAction="http://tempuri.org/IService1/ingresarReporteResponse")]
        int ingresarReporte(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ingresarReporte", ReplyAction="http://tempuri.org/IService1/ingresarReporteResponse")]
        System.Threading.Tasks.Task<int> ingresarReporteAsync(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listaReporteCli", ReplyAction="http://tempuri.org/IService1/listaReporteCliResponse")]
        NoMasAcc2._0.ServicioReportes.ReporteCliente[] listaReporteCli();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listaReporteCli", ReplyAction="http://tempuri.org/IService1/listaReporteCliResponse")]
        System.Threading.Tasks.Task<NoMasAcc2._0.ServicioReportes.ReporteCliente[]> listaReporteCliAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ingresarReporteGlobal", ReplyAction="http://tempuri.org/IService1/ingresarReporteGlobalResponse")]
        int ingresarReporteGlobal(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ingresarReporteGlobal", ReplyAction="http://tempuri.org/IService1/ingresarReporteGlobalResponse")]
        System.Threading.Tasks.Task<int> ingresarReporteGlobalAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listarReporteGlo", ReplyAction="http://tempuri.org/IService1/listarReporteGloResponse")]
        NoMasAcc2._0.ServicioReportes.ReporteGlobal[] listarReporteGlo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listarReporteGlo", ReplyAction="http://tempuri.org/IService1/listarReporteGloResponse")]
        System.Threading.Tasks.Task<NoMasAcc2._0.ServicioReportes.ReporteGlobal[]> listarReporteGloAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : NoMasAcc2._0.ServicioReportes.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<NoMasAcc2._0.ServicioReportes.IService1>, NoMasAcc2._0.ServicioReportes.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ingresarReporte(int idCliente) {
            return base.Channel.ingresarReporte(idCliente);
        }
        
        public System.Threading.Tasks.Task<int> ingresarReporteAsync(int idCliente) {
            return base.Channel.ingresarReporteAsync(idCliente);
        }
        
        public NoMasAcc2._0.ServicioReportes.ReporteCliente[] listaReporteCli() {
            return base.Channel.listaReporteCli();
        }
        
        public System.Threading.Tasks.Task<NoMasAcc2._0.ServicioReportes.ReporteCliente[]> listaReporteCliAsync() {
            return base.Channel.listaReporteCliAsync();
        }
        
        public int ingresarReporteGlobal(int idUsuario) {
            return base.Channel.ingresarReporteGlobal(idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> ingresarReporteGlobalAsync(int idUsuario) {
            return base.Channel.ingresarReporteGlobalAsync(idUsuario);
        }
        
        public NoMasAcc2._0.ServicioReportes.ReporteGlobal[] listarReporteGlo() {
            return base.Channel.listarReporteGlo();
        }
        
        public System.Threading.Tasks.Task<NoMasAcc2._0.ServicioReportes.ReporteGlobal[]> listarReporteGloAsync() {
            return base.Channel.listarReporteGloAsync();
        }
    }
}
